version: '3.5'

networks:
  wallet-js:
    name: wallet-js
    attachable: true
volumes:
  blockstore:
    name: blockstore

services:
  wallet-js-iroha:
    image: hyperledger/iroha:latest
    container_name: wallet-js-iroha
    depends_on:
      - wallet-js-iroha-postgres
    tty: true
    environment:
      - KEY=node0
    networks:
      - wallet-js
    volumes:
      - C:\Users\user\iroha-wallet-js\docker\iroha:/opt/iroha_data
      - blockstore:/tmp/block_store
    ports:
      - 50051:50051

  wallet-js-iroha-postgres:
    image: postgres:9.5
    container_name: wallet-js-iroha-postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
    networks:
      - wallet-js
    ports:
      - 5432:5432

  grpcwebproxy:
    build:
      context: grpcwebproxy/
    container_name: wallet-js-grpcwebproxy
    depends_on:
      - wallet-js-iroha
    entrypoint:
      - grpcwebproxy
      - --backend_addr=wallet-js-iroha:50051
      - --run_tls_server=false
      - --allow_all_origins=true
    networks:
      - wallet-js
    ports:
      - 8081:8080
